name: Music Hub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    name: Frontend build (music-app)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: music-app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: React build
        run: npm run build

  backend:
    name: Backend syntax check (kpop-backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kpop-backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Node syntax check
        run: npm run check
